### ISSUE TITLE
Add axis labels and better color scheme

### ISSUE THREAD

**Issue by kirby561** [kirby561/CryptoRetriever#21]
The graph viewer looks pretty ugly right now. There's no axis labels and you can't see the axis. We want it to look more like this:
![image](https://user-images.githubusercontent.com/836379/158881150-76094928-8e81-4a26-a584-b5a3f83beaa9.png)

**Comment by kirby561** [comment]
Another idea for a followup story to add tickmarks and labels:
![image](https://user-images.githubusercontent.com/836379/158882794-ef12034d-60a8-469c-b014-fd50c5c71508.png)

**Comment by Kyrisx** [comment]
Completed #41
